-   repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: '5f06a63'
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@1.4.4']
        args: ['--write', '--no-semi', '--single-quote', '--trailing-comma', 'all']
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: '7b4a9e9'
    hooks:
    -   id: eslint
        args: ['--fix']
        additional_dependencies:
        - babel-eslint@6.1.2
        - eslint-config-prettier@2.1.1
        - eslint-config-standard@10.2.1
        - eslint-plugin-import@2.3.0
        - eslint-plugin-jsx-a11y@5.0.3
        - eslint-plugin-node@5.0.0
        - eslint-config-standard-react@5.0.0
        - eslint-plugin-prettier@2.1.1
        - eslint-plugin-promise@3.5.0
        - eslint-plugin-react@7.0.1
        - eslint-plugin-standard@3.0.1
        - eslint@3.19.0
        - prettier@1.4.4
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
